# Generated by Django 3.1.4 on 2021-01-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Автор')),
                ('birth_year', models.SmallIntegerField(verbose_name='Год рождения')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Издательство')),
                ('country', models.CharField(max_length=2, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'издательство',
                'verbose_name_plural': 'Издательства',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, verbose_name='Междунар. код')),
                ('title', models.TextField(verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Аннотация')),
                ('year_release', models.SmallIntegerField(verbose_name='Издание')),
                ('copy_count', models.SmallIntegerField(default=1, verbose_name='Экз')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='p_library.author', verbose_name='Автор')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='p_library.publisher', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['publisher'],
            },
        ),
    ]
