# Generated by Django 3.1.4 on 2021-01-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20210109_0839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCopy',
            new_name='BookInstance',
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['data'], 'verbose_name_plural': 'Экземпляры'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
    ]
