# Generated by Django 3.1.4 on 2021-01-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20210109_0857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['book'], 'verbose_name': 'экземпляр', 'verbose_name_plural': 'Экземпляры'},
        ),
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(blank=True, upload_to='cover_book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='p_library.friend', verbose_name='У кого'),
        ),
    ]
